#!/bin/bash
cd ~
project_path="projects"
folder="$(find $project_path -maxdepth 1 -type d -iname *${1}*)"
num=$(find $project_path -maxdepth 1 -type d -iname *${1}* | wc -l)

if [ -n "$folder" ] ; then

  if [ $num == "1" ] ; then
    atom $folder
    echo "~${pwd}/${fname}"
  else
    
    echo "more than one match was found..."

    for fname in $folder
    do
      echo "do you want to open this one (y or n): ${fname}"
      read ANSWER

      if [ $ANSWER == "y" ] ; then
        atom $fname
        echo "~${pwd}/${fname}"
        break
      fi
    done
  fi

else
  echo "No project found"
fi
